apiVersion: launcher.fabric8.io/v1alpha2
kind: Launcher
metadata:
  name: launcher
spec:
  imageTag: latest
  
####### OpenShift Configuration
  openshift:
    apiUrl: https://openshift.default.svc.cluster.local
    consoleUrl: #<the OpenShift Console Url (ex: 'https://192.168.64.4:8443')>#

####### OAuth Configuration
  oauth:
    enabled: true
    keycloakUrl: http://keycloakUrl
    keycloakRealm: launcher
    keycloakClientId: launcher

  git:
    providers:
    - id: GitHub
      clientId: "12"
      clientSecret: "12"
