apiVersion: launcher.fabric8.io/v1alpha2
kind: Launcher
metadata:
  name: launcher
spec:

####### OpenShift Configuration
  openshift:
    apiUrl: https://openshift.default.svc.cluster.local
    consoleUrl: #<the OpenShift Console Url (ex: 'https://console-openshift-console.apps-crc.testing')>#

####### OAuth Configuration
  oauth:
    enabled: true
#    keycloakUrl: http://keycloakUrl
#    keycloakRealm: launcher
#    keycloakClientId: launcher

    # see: https://docs.openshift.com/container-platform/4.1/authentication/configuring-internal-oauth.html#oauth-server-metadata_configuring-internal-oauth
    # for 3.x you can omit this
    url: # https://oauth-openshift.apps-crc.testing/oauth/authorize#

  git:
    providers:
    - id: GitHub
      clientId: "12"
      clientSecret: "12"
      oauthUrl: "https://github.com/login/oauth/access_token"
