apiVersion: launcher.fabric8.io/v1alpha1
kind: Launcher
metadata:
  name: launcher
spec:
  git:
    provider: github
    token:
      valueFrom:
        secretKeyRef:
          name: launcher-secrets
          key: github-token
