apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: launchers.launcher.fabric8.io
spec:
  group: launcher.fabric8.io
  names:
    kind: Launcher
    listKind: LauncherList
    plural: launchers
    singular: launcher
  scope: Namespaced
  version: v1alpha2
  subresources:
    status: {}
